apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: plex.tce.rhmlab.local.
  labels:
    app: plexserver
  name: plex-httpproxy
  namespace: plex
spec:
  routes:
  - conditions:
    - prefix: /
    pathRewritePolicy:
      replacePrefix:
      - prefix: /
        replacement: /
    services:
    - name: plex-tcp
      port: 32400
  virtualhost:
    fqdn: plex.tce.rhmlab.local
    tls:
      secretName: plex-tls