apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: plex-issuer
  namespace: plex
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plex-tls
  namespace: plex
spec:
  secretName: plex-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - rhmlab
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - plex.tce.rhmlab.local
  ipAddresses:
    - 192.168.151.62
  issuerRef:
    name: plex-issuer
    kind: Issuer
    group: cert-manager.io